// Every word the extension shows, in English and Arabic. build.mjs turns these into
// _locales/*/messages.json; at run time the browser picks the language (chrome.i18n), and
// i18n.ts fills {placeholders}. Voice and terms follow the web app (web/src/lib/i18n.ts).

export const en = {
  extName: 'Keyra Companion',
  extDescription: "Types your logins into websites from your Keyra — after a press of its button. It never sees a stored password.",

  // In the page
  iconLabel: 'Keyra: logins for this site',
  menuFor: 'Logins for {host}',
  menuEmpty: 'No login saved for {host}.',
  menuOther: 'Other login…',
  menuGenerate: 'Strong password from Keyra',
  menuGenerateSub: 'Fills the new password and its confirmation',
  menuFoot: 'Keyra types it after you press its button.',
  menuSearch: 'Search all logins',
  menuNoResults: 'No matches',
  menuLoading: 'Asking Keyra…',
  back: 'Back',
  warnTitle: 'This login is for another site',
  warnBody: '“{title}” is saved for {login}, but this page is {page}. Type it here only if you trust this page with it.',
  warnContinue: 'Type it here anyway',
  cancel: 'Cancel',
  close: 'Close',
  tryAgain: 'Try again',
  pressTitle: "Press Keyra's button",
  pressBody: 'Keyra types into the highlighted field.',
  pressSaveBody: 'Keyra saves it when you press.',
  pressHold: 'Or hold the button for 2 seconds to cancel.',
  pressFor: 'for {host}',
  chipUsername: 'Username',
  chipPassword: 'Password',
  chipBoth: 'Both',
  chipSave: 'Save',
  chipUpdate: 'Update',
  typing: 'Typing…',
  typedTitle: 'Typed',
  typedBody: 'Done. Keyra is ready for the next one.',
  savedTitle: 'Saved to Keyra',
  savedBody: 'You can type it from Keyra next time.',
  updatedTitle: 'Password updated',
  updatedBody: 'The old one is in its password history.',
  cancelledTitle: 'Cancelled',
  expiredTitle: 'That took too long',
  expiredBody: 'Keyra waited 60 seconds. Try again when you are ready.',
  failNoUsbTitle: "Keyra isn't plugged in",
  failNoUsbBody: "Plug Keyra into this computer's USB port, then try again.",
  failNoHostTitle: "The computer didn't connect",
  failNoHostBody: 'Check that Bluetooth is on and paired with Keyra, then try again.',
  failHostChangedTitle: 'Keyra moved to another computer',
  failHostChangedBody: 'It was unplugged while waiting. Plug it in here and try again.',
  failUnsupportedTitle: "Keyra can't type this one",
  failUnsupportedBody: 'It has a character outside the standard keyboard. Change the password in the Keyra app.',
  failTitle: "Couldn't do it",
  failBody: 'Keyra answered “{code}”. Click the field and try again.',
  errLockedTitle: 'Keyra is locked',
  errLockedBody: 'Unlock it in the Keyra app, then try again.',
  errUnreachableTitle: "Can't reach Keyra",
  errUnreachableBody: 'Is this computer on the same network as Keyra ({address})?',
  errTokenTitle: "This browser isn't connected anymore",
  errTokenBody: 'Its access token was revoked. Connect again from the Keyra button in the toolbar.',
  errForbiddenTitle: "This token isn't for a browser extension",
  errForbiddenBody: 'Connect again from the Keyra button in the toolbar.',
  errBusyTitle: 'Keyra is waiting for another request',
  errBusyBody: 'Hold its button for 2 seconds to cancel it, then try again.',
  errRateTitle: 'Too many requests',
  errRateBody: 'Keyra answers up to 10 requests in 10 seconds. Try again in a moment.',
  errNotFoundTitle: 'That login is gone',
  errNotFoundBody: "It was deleted, or it isn't shared with this browser.",
  errNotConnectedTitle: "Keyra isn't connected",
  errNotConnectedBody: 'Click the Keyra button in the toolbar to connect.',
  errTitle: 'Something went wrong',
  openKeyra: 'Open Keyra',
  saveTitle: 'Save to Keyra?',
  updateTitle: 'Update the password for {title}?',
  updateBody: 'The old one stays in its password history.',
  saveSite: 'Site',
  saveUser: 'Username',
  saveNoUser: 'No username',
  saveAction: 'Save',
  updateAction: 'Update',
  notNow: 'Not now',
  never: 'Never for this site',
  generatedTitle: 'Strong password filled in',
  generatedBody: 'Keyra offers to save it when you send the form.',

  // Toolbar popup
  stReady: 'Ready',
  stLocked: 'Locked',
  stOffline: 'Offline',
  stNotConnected: 'Not connected',
  tabLogins: 'Logins',
  tabGenerator: 'Generator',
  tabSettings: 'Settings',
  connectTitle: 'Connect your Keyra',
  connectBody: 'Pick a login on a website and Keyra types it after you press its button. This browser never sees a stored password.',
  addressLabel: "Keyra's address",
  addressHelp: 'Home Wi‑Fi: http://keyra.local · Keyra’s own Wi‑Fi: http://192.168.4.1',
  addressBad: 'Enter an address like http://keyra.local.',
  connectAction: 'Connect',
  connectSteps: "A Keyra tab opens. Unlock it if asked, confirm, then press Keyra's button. The tab closes by itself.",
  connectWaiting: 'Finish in the Keyra tab…',
  connectNoPermission: "Allow access to Keyra's address to connect.",
  connectNotKeyra: 'No Keyra answered at {address}.',
  connectUninit: "This Keyra isn't set up yet. Open it and set it up first.",
  connectDone: 'Connected to Keyra',
  pasteToggle: 'Paste a token instead',
  pasteLabel: 'Access token',
  pasteHelp: 'Create one in Keyra → Settings → Apps and agents, used by “Browser extension”.',
  pasteAction: 'Save token',
  pasteBad: "That isn't a Keyra access token.",
  lockedBody: 'Unlock it to use your logins.',
  offlineBody: 'Is this computer on the same network as Keyra? ({address})',
  invalidTitle: 'Connection revoked',
  invalidBody: "This browser's access token no longer works.",
  connectAgain: 'Connect again',
  onThisSite: 'On {host}',
  noLoginsHere: 'No saved login for this site.',
  noPage: 'Open a website to see its logins.',
  allLogins: 'All logins',
  typeHere: 'Type into this page',
  typeHereSub: 'Opens the press card on the page',
  noField: 'No login field on this page. Click into one first.',
  genNew: 'New one',
  genCopy: 'Copy',
  genCopied: 'Copied',
  genLength: 'Length',
  genDigits: 'Numbers 0–9',
  genSymbols: 'Symbols !@#$',
  genBits: 'Strong · {bits} bits',
  genBitsWeak: '{bits} bits — make it longer',
  genNote: "Made by Keyra's hardware random generator. Not saved anywhere.",
  setAddress: "Keyra's address",
  setIcons: 'Show the Keyra icon in login fields',
  setSave: 'Offer to save new logins',
  setNever: 'Never offer to save on',
  setNeverNone: 'No sites yet.',
  setRemove: 'Remove {host}',
  setDisconnect: 'Disconnect this browser',
  setDisconnectNote: 'Also revoke its token in Keyra → Settings → Apps and agents.',
  setPrivacy: 'Keyra Companion sends Keyra only the host of the page you are on. Passwords stay on Keyra.',
  version: 'Version {v}',
};

export type Key = keyof typeof en;

export const ar: Record<Key, string> = {
  extName: 'Keyra Companion',
  extDescription: 'يكتب حساباتك في المواقع من Keyra بعد ضغطة زرّه. لا يرى أي كلمة مرور مخزّنة.',

  iconLabel: 'Keyra: حسابات هذا الموقع',
  menuFor: 'حسابات {host}',
  menuEmpty: 'لا يوجد حساب محفوظ لـ {host}.',
  menuOther: 'حساب آخر…',
  menuGenerate: 'كلمة مرور قوية من Keyra',
  menuGenerateSub: 'تملأ كلمة المرور الجديدة وتأكيدها',
  menuFoot: 'يكتبه Keyra بعد أن تضغط زرّه.',
  menuSearch: 'ابحث في كل الحسابات',
  menuNoResults: 'لا نتائج',
  menuLoading: 'جارٍ سؤال Keyra…',
  back: 'رجوع',
  warnTitle: 'هذا الحساب لموقع آخر',
  warnBody: '«{title}» محفوظ لـ {login}، لكن هذه الصفحة هي {page}. اكتبه هنا فقط إن كنت تثق بهذه الصفحة.',
  warnContinue: 'اكتبه هنا رغم ذلك',
  cancel: 'إلغاء',
  close: 'إغلاق',
  tryAgain: 'حاول مجدداً',
  pressTitle: 'اضغط زرّ Keyra',
  pressBody: 'يكتب Keyra في الخانة المحدّدة.',
  pressSaveBody: 'يحفظه Keyra عندما تضغط.',
  pressHold: 'أو اضغط الزر مطوّلاً ثانيتين للإلغاء.',
  pressFor: 'لـ {host}',
  chipUsername: 'اسم المستخدم',
  chipPassword: 'كلمة المرور',
  chipBoth: 'الاثنان',
  chipSave: 'حفظ',
  chipUpdate: 'تحديث',
  typing: 'جارٍ الكتابة…',
  typedTitle: 'تمّت الكتابة',
  typedBody: 'تم. Keyra جاهز للمرة التالية.',
  savedTitle: 'حُفظ في Keyra',
  savedBody: 'يمكنك كتابته من Keyra في المرة القادمة.',
  updatedTitle: 'حُدّثت كلمة المرور',
  updatedBody: 'القديمة في سجلّ كلمات مروره.',
  cancelledTitle: 'أُلغي',
  expiredTitle: 'استغرق الأمر وقتاً طويلاً',
  expiredBody: 'انتظر Keyra ‏60 ثانية. حاول مجدداً عندما تكون جاهزاً.',
  failNoUsbTitle: 'Keyra غير موصول',
  failNoUsbBody: 'صِل Keyra بمنفذ USB في هذا الكمبيوتر، ثم حاول مجدداً.',
  failNoHostTitle: 'لم يتصل الكمبيوتر',
  failNoHostBody: 'تأكد أن البلوتوث يعمل ومقترن بـ Keyra، ثم حاول مجدداً.',
  failHostChangedTitle: 'انتقل Keyra إلى كمبيوتر آخر',
  failHostChangedBody: 'فُصل أثناء الانتظار. صِله هنا وحاول مجدداً.',
  failUnsupportedTitle: 'لا يستطيع Keyra كتابة هذه',
  failUnsupportedBody: 'فيها حرف خارج لوحة المفاتيح القياسية. غيّر كلمة المرور في تطبيق Keyra.',
  failTitle: 'تعذّر ذلك',
  failBody: 'أجاب Keyra بـ «{code}». انقر على الخانة وحاول مجدداً.',
  errLockedTitle: 'Keyra مقفل',
  errLockedBody: 'افتح قفله في تطبيق Keyra، ثم حاول مجدداً.',
  errUnreachableTitle: 'تعذّر الوصول إلى Keyra',
  errUnreachableBody: 'هل هذا الكمبيوتر على نفس شبكة Keyra ‏({address})؟',
  errTokenTitle: 'هذا المتصفح لم يعد مربوطاً',
  errTokenBody: 'أُلغي رمز الوصول الخاص به. اربطه مجدداً من زر Keyra في شريط الأدوات.',
  errForbiddenTitle: 'هذا الرمز ليس لإضافة متصفح',
  errForbiddenBody: 'اربطه مجدداً من زر Keyra في شريط الأدوات.',
  errBusyTitle: 'Keyra ينتظر طلباً آخر',
  errBusyBody: 'اضغط زرّه مطوّلاً ثانيتين لإلغائه، ثم حاول مجدداً.',
  errRateTitle: 'طلبات كثيرة',
  errRateBody: 'يجيب Keyra عن 10 طلبات كل 10 ثوانٍ. حاول مجدداً بعد لحظة.',
  errNotFoundTitle: 'هذا الحساب لم يعد موجوداً',
  errNotFoundBody: 'حُذف، أو أنه غير مشارَك مع هذا المتصفح.',
  errNotConnectedTitle: 'Keyra غير مربوط',
  errNotConnectedBody: 'انقر زر Keyra في شريط الأدوات للربط.',
  errTitle: 'حدث خطأ',
  openKeyra: 'افتح Keyra',
  saveTitle: 'حفظ في Keyra؟',
  updateTitle: 'تحديث كلمة المرور لـ {title}؟',
  updateBody: 'تبقى القديمة في سجلّ كلمات مروره.',
  saveSite: 'الموقع',
  saveUser: 'اسم المستخدم',
  saveNoUser: 'بلا اسم مستخدم',
  saveAction: 'حفظ',
  updateAction: 'تحديث',
  notNow: 'ليس الآن',
  never: 'أبداً لهذا الموقع',
  generatedTitle: 'عُبّئت كلمة مرور قوية',
  generatedBody: 'سيعرض Keyra حفظها عندما ترسل النموذج.',

  stReady: 'جاهز',
  stLocked: 'مقفل',
  stOffline: 'غير متاح',
  stNotConnected: 'غير مربوط',
  tabLogins: 'الحسابات',
  tabGenerator: 'المولّد',
  tabSettings: 'الإعدادات',
  connectTitle: 'اربط Keyra',
  connectBody: 'اختر حساباً في أي موقع ويكتبه Keyra بعد أن تضغط زرّه. لا يرى هذا المتصفح أي كلمة مرور مخزّنة.',
  addressLabel: 'عنوان Keyra',
  addressHelp: 'Wi‑Fi المنزل: ⁦http://keyra.local⁩ · شبكة Keyra نفسه: ⁦http://192.168.4.1⁩',
  addressBad: 'أدخل عنواناً مثل http://keyra.local.',
  connectAction: 'اربط',
  connectSteps: 'يُفتح تبويب Keyra. افتح القفل إن طُلب منك، ثم أكّد واضغط زرّ Keyra. يُغلق التبويب وحده.',
  connectWaiting: 'أكمل في تبويب Keyra…',
  connectNoPermission: 'اسمح بالوصول إلى عنوان Keyra لإتمام الربط.',
  connectNotKeyra: 'لم يُجب أي Keyra على {address}.',
  connectUninit: 'Keyra هذا غير مُعدّ بعد. افتحه وأعدّه أولاً.',
  connectDone: 'رُبط بـ Keyra',
  pasteToggle: 'الصق رمزاً بدلاً من ذلك',
  pasteLabel: 'رمز الوصول',
  pasteHelp: 'أنشئه في Keyra ← الإعدادات ← التطبيقات والوكلاء، واختر «إضافة متصفح».',
  pasteAction: 'احفظ الرمز',
  pasteBad: 'هذا ليس رمز وصول من Keyra.',
  lockedBody: 'افتح قفله لتستخدم حساباتك.',
  offlineBody: 'هل هذا الكمبيوتر على نفس شبكة Keyra؟ ({address})',
  invalidTitle: 'أُلغي الربط',
  invalidBody: 'رمز الوصول لهذا المتصفح لم يعد يعمل.',
  connectAgain: 'اربط مجدداً',
  onThisSite: 'على {host}',
  noLoginsHere: 'لا يوجد حساب محفوظ لهذا الموقع.',
  noPage: 'افتح موقعاً لترى حساباته.',
  allLogins: 'كل الحسابات',
  typeHere: 'اكتب في هذه الصفحة',
  typeHereSub: 'تظهر بطاقة الضغط في الصفحة',
  noField: 'لا توجد خانة دخول في هذه الصفحة. انقر داخل واحدة أولاً.',
  genNew: 'واحدة جديدة',
  genCopy: 'نسخ',
  genCopied: 'تم النسخ',
  genLength: 'الطول',
  genDigits: 'أرقام ⁦0–9⁩',
  genSymbols: 'رموز ⁦!@#$⁩',
  genBits: 'قوية · {bits} بت',
  genBitsWeak: '{bits} بت — اجعلها أطول',
  genNote: 'يولّدها مولّد Keyra العشوائي العتادي. لا تُحفظ في أي مكان.',
  setAddress: 'عنوان Keyra',
  setIcons: 'أظهر أيقونة Keyra في خانات الدخول',
  setSave: 'اعرض حفظ الحسابات الجديدة',
  setNever: 'لا تعرض الحفظ أبداً على',
  setNeverNone: 'لا مواقع بعد.',
  setRemove: 'أزل {host}',
  setDisconnect: 'افصل هذا المتصفح',
  setDisconnectNote: 'وألغِ رمزه أيضاً في Keyra ← الإعدادات ← التطبيقات والوكلاء.',
  setPrivacy: 'يرسل Keyra Companion إلى Keyra اسم مضيف الصفحة فقط. كلمات المرور تبقى في Keyra.',
  version: 'الإصدار {v}',
};
