add_executable(keyra_net_dns_test dns_packet_test.cpp ../src/dns_packet.cpp)
add_executable(keyra_net_link_test link_test.cpp ../src/link.cpp)
add_executable(keyra_net_addr_test addr_test.cpp ../src/addr.cpp ../src/scan_list.cpp)
foreach(t dns link addr)
  target_include_directories(keyra_net_${t}_test PRIVATE ../src ../include)
  add_test(NAME keyra_net_${t} COMMAND keyra_net_${t}_test)
endforeach()
