#!/usr/bin/env python3
"""Builds the independent reverse table the layout host test checks Keyra's
tables against: for every key press, the character the Unicode CLDR keyboard
data (release 43) says the host types. CLDR is a different source from the
one layouts.txt is built from (Microsoft's DLLs via kbdlayout.info, and the
running macOS), so a mistake in either shows up as a test failure.

Usage:
  mkdir -p cldr && for f in $(python3 tools/layouts/cldr_reverse.py --files); do
    curl -sL -o cldr/$(basename $f) https://raw.githubusercontent.com/unicode-org/cldr/release-43/keyboards/$f; done
  python3 tools/layouts/cldr_reverse.py cldr/ > firmware/components/keyra_hid/host_test/cldr_reverse.inc
"""
import pathlib
import re
import sys
import unicodedata
import xml.etree.ElementTree as ET

# layout id -> (CLDR file, platform, layers checked). CLDR has no data for
# today's macOS "Spanish" (its osx file is "Spanish – Legacy"), "Italian" (its
# file is the old layout now called "Italian – QZERTY") or "Arabic – PC": those
# three are checked only against the OS dump and on hardware.
SOURCES = {
    "us": ("windows/en-t-k0-windows.xml", "win", 2),
    "uk": ("windows/en-GB-t-k0-windows.xml", "win", 4),
    "uk-mac": ("osx/en-GB-t-k0-osx.xml", "mac", 4),
    "de": ("windows/de-t-k0-windows.xml", "win", 4),
    "de-mac": ("osx/de-t-k0-osx.xml", "mac", 4),
    "fr": ("windows/fr-t-k0-windows.xml", "win", 4),
    "fr-mac": ("osx/fr-t-k0-osx.xml", "mac", 4),
    "es": ("windows/es-t-k0-windows.xml", "win", 4),
    "it": ("windows/it-t-k0-windows.xml", "win", 4),
    "dvorak": ("windows/en-t-k0-windows-dvorak.xml", "win", 2),
    "colemak": ("osx/en-t-k0-osx-colemak.xml", "mac", 2),
    "ar": ("windows/ar-t-k0-windows.xml", "win", 4),
    "ar-mac": ("osx/ar-t-k0-osx.xml", "mac", 4),
}

ISO = {"E00": 0x35, "E11": 0x2D, "E12": 0x2E, "D11": 0x2F, "D12": 0x30, "D13": 0x31, "C10": 0x33,
       "C11": 0x34, "C12": 0x31, "B00": 0x64, "B08": 0x36, "B09": 0x37, "B10": 0x38, "A03": 0x2C}
for i in range(10):
    ISO[f"E{i + 1:02d}"] = 0x1E + i
for row, letters in (("D", "qwertyuiop"), ("C", "asdfghjkl"), ("B", "zxcvbnm")):
    for i, ch in enumerate(letters):
        ISO[f"{row}{i + 1:02d}"] = 0x04 + ord(ch) - ord("a")

PRESSED = {"win": [set(), {"shiftL"}, {"altR"}, {"shiftL", "altR"}],
           "mac": [set(), {"shiftL"}, {"optL"}, {"shiftL", "optL"}]}


def covers(token, key):
    base = token.rstrip("?")
    if base == key:
        return True
    return base in ("shift", "alt", "opt", "ctrl", "cmd") and key[:-1] == base


def matches(attr, pressed):
    if attr is None:
        return not pressed
    for alt in attr.split():
        tokens = alt.split("+")
        required = [t for t in tokens if not t.endswith("?")]
        if not all(any(covers(t, k) for k in pressed) for t in required):
            continue
        if all(any(covers(t, k) for t in tokens) for k in pressed):
            return True
    return False


def unescape(s):
    return re.sub(r"\\u\{([0-9A-Fa-f]+)\}", lambda m: chr(int(m.group(1), 16)), s)


def keep(s):
    if len(s) != 1:
        return False
    cp = ord(s)
    if cp == 0x20:
        return True
    cat = unicodedata.category(s)
    return cp <= 0xFFFF and cat[0] not in "CZ"


def main():
    if sys.argv[1:] == ["--files"]:
        print(" ".join(f for f, _, _ in SOURCES.values()))
        return
    root = pathlib.Path(sys.argv[1])
    print("// Generated by tools/layouts/cldr_reverse.py from Unicode CLDR release 43 keyboard data")
    print("// (Unicode License v3). {layout, HID usage, layer, character, dead}: dead keys give the")
    print("// character they type when followed by Space. Layers: 0 base, 1 Shift, 2 AltGr/Option, 3 both.")
    for ident, (path, platform, layers) in SOURCES.items():
        doc = ET.parse(root / pathlib.Path(path).name).getroot()
        transforms = {}
        for t in doc.iter("transform"):
            transforms[unescape(t.get("from"))] = unescape(t.get("to"))
        prefixes = {k[:-1] for k in transforms if len(k) > 1}
        for layer in range(layers):
            pressed = PRESSED[platform][layer]
            maps = [km for km in doc.iter("keyMap") if matches(km.get("modifiers"), pressed)]
            if not maps:
                continue
            for m in maps[0].iter("map"):
                usage = ISO.get(m.get("iso"))
                if usage is None or (usage == 0x2C and layer > 0):
                    continue
                out = unescape(m.get("to"))
                dead = out in prefixes and m.get("transform") != "no"
                if dead:
                    out = transforms.get(out + " ", "")
                if keep(out):
                    print(f'{{"{ident}", 0x{usage:02X}, {layer}, 0x{ord(out):04X}, {str(dead).lower()}}},')


if __name__ == "__main__":
    main()
